name: CI - build & smoke test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ai-triage:ci .

      - name: Run container (with safe defaults)
        run: |
          docker run -d --name ai-triage -p 8000:8000 \
            -e API_KEYS="demo-key-1" \
            -e DB_PATH="/app/data/triage.db" \
            -e TRIAGE_PROVIDER="rules" \
            ai-triage:ci

      - name: Wait for server to be ready
        run: |
          for i in {1..40}; do
            curl -fsS http://localhost:8000/readyz && break
            sleep 1
          done

      - name: Smoke tests
        run: |
          # Swagger should load unauth'd
          curl -fsS http://localhost:8000/docs >/dev/null
          # Auth'd health should also succeed
          curl -fsS -H "x-api-key: demo-key-1" http://localhost:8000/health >/dev/null
